.TH CFBS "1" "2025\-08\-14" "cfbs" "CFEngine Build System manual"
.SH NAME
cfbs \- combines multiple modules into 1 policy set to deploy on your infrastructure. Modules can be custom promise types, JSON files which enable certain functionality, or reusable CFEngine policy. The modules you use can be written by the CFEngine team, others in the community, your colleagues, or yourself.
.SH SYNOPSIS
.B cfbs
[-h] [--loglevel LOGLEVEL] [-M] [--version] [--force] [--non-interactive] [--index INDEX] [--check] [--checksum CHECKSUM] [--keep-order] [--git {yes,no}] [--git-user-name GIT_USER_NAME] [--git-user-email GIT_USER_EMAIL] [--git-commit-message GIT_COMMIT_MESSAGE] [--ignore-versions-json] [--omit-download] [--check-against-git] [--from MINIMUM_VERSION] [--to-json [TO_JSON]] [--reference-version REFERENCE_VERSION] [--masterfiles-dir MASTERFILES_DIR] [--ignored-path-components [IGNORED_PATH_COMPONENTS ...]] [--offline] [--masterfiles MASTERFILES] [cmd] [args ...]
.SH DESCRIPTION
CFEngine Build System.

.TP
\fBcmd\fR
The command to perform (pretty, init, status, search, add, remove, clean, update, validate, download, build, install, help, info, show, analyse, analyze, convert, input, set\-input, get\-input, generate\-release\-information)

.TP
\fBargs\fR
Command arguments

.SH OPTIONS
.TP
\fB\-\-loglevel\fR \fI\,LOGLEVEL\/\fR, \fB\-l\fR \fI\,LOGLEVEL\/\fR
Set log level for more/less detailed output

.TP
\fB\-M\fR, \fB\-\-manual\fR
Print manual page

.TP
\fB\-\-version\fR, \fB\-V\fR
Print version number

.TP
\fB\-\-force\fR
Force rebuild / redownload

.TP
\fB\-\-non\-interactive\fR
Don't prompt, use defaults (only for testing)

.TP
\fB\-\-index\fR \fI\,INDEX\/\fR
Specify alternate index (HTTPS URL or relative path to JSON file)

.TP
\fB\-\-check\fR
Check if file(s) would be reformatted

.TP
\fB\-\-checksum\fR \fI\,CHECKSUM\/\fR
Expected checksum of the downloaded file

.TP
\fB\-\-keep\-order\fR
Keep order of items in the JSON in 'cfbs pretty'

.TP
\fB\-\-git\fR \fI\,{yes,no}\/\fR
Override git option in cfbs.json

.TP
\fB\-\-git\-user\-name\fR \fI\,GIT_USER_NAME\/\fR
Specify git user name

.TP
\fB\-\-git\-user\-email\fR \fI\,GIT_USER_EMAIL\/\fR
Specify git user email

.TP
\fB\-\-git\-commit\-message\fR \fI\,GIT_COMMIT_MESSAGE\/\fR
Specify git commit message

.TP
\fB\-\-ignore\-versions\-json\fR
Ignore versions.json. Necessary in case of a custom index or testing changes to the default index.

.TP
\fB\-\-omit\-download\fR
Use existing masterfiles instead of downloading in 'cfbs generate\-release\-information'

.TP
\fB\-\-check\-against\-git\fR
Check whether masterfiles from cfengine.com and github.com match in 'cfbs generate\-release\-information'

.TP
\fB\-\-from\fR \fI\,MINIMUM_VERSION\/\fR
Specify minimum version in 'cfbs generate\-release\-information'

.TP
\fB\-\-to\-json\fR \fI\,[TO_JSON]\/\fR
Output 'cfbs analyze' results to a JSON file; optionally specify the JSON's filename

.TP
\fB\-\-reference\-version\fR \fI\,REFERENCE_VERSION\/\fR
Specify version to compare against for 'cfbs analyze'

.TP
\fB\-\-masterfiles\-dir\fR \fI\,MASTERFILES_DIR\/\fR
If the path given to 'cfbs analyze' contains a masterfiles subdirectory, specify the subdirectory's name

.TP
\fB\-\-ignored\-path\-components\fR \fI\,[IGNORED_PATH_COMPONENTS ...]\/\fR
Specify path components which should be ignored during 'cfbs analyze' (the components should be passed separately, delimited by spaces)

.TP
\fB\-\-offline\fR
Do not connect to the Internet to download the latest version of MPF release information during 'cfbs analyze' and 'cfbs convert'

.TP
\fB\-\-masterfiles\fR \fI\,MASTERFILES\/\fR
Specify masterfiles version to add during "cfbs init". This can be a branch, a full version number, or `no` to not add masterfiles at all.

.br
Binary packages may be downloaded from https://cfengine.com/download/.
.br
The source code is available at https://github.com/cfengine/
.SH BUGS
Please see the public bug-tracker at https://northerntech.atlassian.net/projects/CFE/.
.br
GitHub pull-requests may be submitted to https://github.com/cfengine/cfbs.
.SH "SEE ALSO"
.BR cf-promises (8),
.BR cf-agent (8),
.BR cf-serverd (8),
.BR cf-execd (8),
.BR cf-monitord (8),
.BR cf-runagent (8),
.BR cf-key (8)
.SH AUTHOR
    Northern.tech AS
        