name: Add, validate, and build all modules

# Controls when the workflow will run
on:
  # Triggers the workflow on master every night at 3:15 am
  schedule:
    - cron: "15 3 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install cfbs with pip
        run: pip3 install cfbs

      # Downloading cfbs.json is needed to run this action in another repo, like cfengine/cfbs:
      - name: Run test script
        run: bash .github/workflows/add_validate_build_all.sh
