name: Automatically format with Black and submit PR

on:
    push:
        branches:
          - master

    workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6]
    steps:
        - name: Checks-out repository
          uses: actions/checkout@v2

        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install black
          run: |
            python -m pip install --upgrade pip
            python -m pip install black
        - name: Reformat with black
          run: |
            black cfbs/*.py test/*.py > black_output.txt
        - name: Create commit message
          run: |
            echo "Output from black:" >> commit_message.txt
            echo "" >> commit_message.txt
            echo '```' >> commit_message.txt
            cat black_output.txt >> commit_message.txt
            echo '```' >> commit_message.txt
        - name: Commit changes
          run: |
            git config user.name 'GitHub'
            git config user.email '<noreply@github.com>'
            git add cfbs/*.py test/*.py
            git commit -F commit_message.txt || echo "No formatting changes"
        - id: commit-message-from-file
          name: Parse commit message from file into variable
          run: |
            body=$(cat commit_message.txt)
            body="${body//$'\n'/'%0A'}"
            echo ::set-output name=body::$body
        - name: Create Pull Request
          uses: cfengine/create-pull-request@v3
          with:
            title: Reformatted python code using Black formatter
            body: ${{ steps.commit-message-from-file.outputs.body }}
            reviewers: |
              olehermanse
              larsewi
            branch: formatting-action
