# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python validate test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-legacy:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    env:
      # Temporary workaround for Python 3.5 failures - May 2024, see CFE-4395
      PIP_TRUSTED_HOST: "pypi.python.org pypi.org files.pythonhosted.org"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.5.10"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up legacy Python ${{ matrix.python-version }}
        uses: ./.github/actions/set-up-legacy-python
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          python setup.py sdist bdist_wheel
          pip install dist/cfbs-*.whl
      - name: Run bash tests
        run: |
          bash tests/shell/validate.sh
